apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica-set-pod
  labels:
    app: node
spec:
  template:
    metadata:
      name: my-pod
      labels:
        app: node
    spec:
      containers:
        - name: myfirst-container
          image: basuhadimani94/create-react-docker-image
  replicas: 3
  selector:
    matchLabels:
      app: node
